codecov:
  bot: "codecov"
  require_ci_to_pass: yes
coverage:
  round: down
  range: 90..100
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        branches:
          - master
          - dev
        if_ci_failed: error
comment:
  layout: "diff,files"
  behavior: default
  require_changes: no